version: '3'

services:
  pg:
    image: postgres:16
    container_name: pg-mistral
    restart: always
    networks:
      - network
    environment:
      - POSTGRES_DB=${PG_NAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mistral:
    depends_on:
      pg:
        condition: service_healthy
    image: mistral
    container_name: mistral
    restart: always
    networks:
      - network
      - sinhron
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "${HTTP_PORT}:5641"

networks:
  sinhron:
    external: true
  network:
    driver: bridge